import { forwardRef } from 'react';
import type { ChuniData } from '../types';
import { getRatingStyle } from '../utils/rating';
import { calculatePlayRate } from '../utils/stats';
import StatCard from './StatCard';
import DifficultySummary from '../features/DifficultySummary';

interface ExportViewProps {
	data: ChuniData;
}

const valueBaseStyle = 'text-4xl md:text-5xl font-black tracking-tighter leading-none';

export const ExportView = forwardRef<HTMLDivElement, ExportViewProps>(({ data }, ref) => {
	const { player } = data;
	const playRate = calculatePlayRate(data.scores).toFixed(1);

	return (
		<div
			ref={ref}
			className="bg-slate-50 font-sans text-slate-900"
			style={{ width: '1280px', minHeight: '800px', padding: '60px' }}
		>
			<div className="space-y-10">
				{/* === ヘッダー === */}
				<div className="flex justify-between items-end border-b-4 border-blue-600 pb-4">
					<h1 className="text-5xl font-black tracking-tighter text-blue-600">CHUNI SCOPE</h1>
					<span className="text-slate-400 font-bold text-xl">PLAYER RESULT CARD</span>
				</div>

				{/* === 1. プロフィール (横並び固定) === */}
				<div className="bg-white rounded-3xl shadow-none border-2 border-slate-200 p-8 border border-slate-100 flex items-center justify-between">
					<div>
						<div className="text-sm font-bold text-slate-400 tracking-widest mb-1">PLAYER</div>
						<div className="flex items-baseline gap-4">
							<div className="text-5xl font-black text-slate-800">{player.name}</div>
						</div>
					</div>
					{/* 右側のスタッツも横並び固定 */}
					<div className="flex gap-12 text-right">
						<div>
							<div className="text-sm font-bold text-slate-400 tracking-widest">RATING</div>
							<p className={`${valueBaseStyle} ${getRatingStyle(data.player.rating)}`}>
								{data.player.rating}
							</p>
						</div>
						<div>
							<div className="text-sm font-bold text-slate-400 tracking-widest">OVERPOWER</div>
							<div className="text-4xl font-black text-slate-700">{player.overpower}</div>
						</div>
						<div className="text-sm font-bold text-slate-400 tracking-widest">
							<p>PLAY RATE</p>
							<p className="text-4xl font-black text-slate-700">
								{playRate}
								<span className="text-2xl md:text-3xl ml-1">%</span>
							</p>
						</div>
					</div>
				</div>

				{/* === 2. 統計カード (5列固定) === */}
				<div>
					<h3 className="text-2xl font-bold mb-6 flex items-center gap-3">
						<span className="w-2 h-8 bg-orange-500 rounded-full"></span>
						All Record Statistics{' '}
						<span className="text-slate-400 text-lg font-normal ml-2">(MASTER & ULTIMA)</span>
					</h3>
					{/* grid-cols-1 md:grid-cols-5 ではなく、常に grid-cols-5 */}
					<div className="grid grid-cols-5 gap-6">
						<StatCard
							label="SSS"
							mascount={data.totals.master.sss}
							mastotal={data.totals.master.total}
							ultcount={data.totals.ultima.sss}
							ulttotal={data.totals.ultima.total}
							colorKey="rose"
							isExport={true}
						/>
						<StatCard
							label="SSS"
							mascount={data.totals.master.sssPlus}
							mastotal={data.totals.master.total}
							ultcount={data.totals.ultima.sssPlus}
							ulttotal={data.totals.ultima.total}
							colorKey="red"
							isExport={true}
						/>
						<StatCard
							label="AJ"
							mascount={data.totals.master.aj}
							mastotal={data.totals.master.total}
							ultcount={data.totals.ultima.aj}
							ulttotal={data.totals.ultima.total}
							colorKey="orange"
							isExport={true}
						/>
						<StatCard
							label="AJC"
							mascount={data.totals.master.ajc}
							mastotal={data.totals.master.total}
							ultcount={data.totals.ultima.ajc}
							ulttotal={data.totals.ultima.total}
							colorKey="yellow"
							isExport={true}
						/>
						<StatCard
							label="FULLCHAIN"
							mascount={data.totals.master.fc}
							mastotal={data.totals.master.total}
							ultcount={data.totals.ultima.fc}
							ulttotal={data.totals.ultima.total}
							colorKey="emerald"
							isExport={true}
						/>
					</div>
				</div>

				{/* === 3. 難易度別サマリー (6列固定) === */}
				<div>
					<h3 className="text-2xl font-bold mb-6 flex items-center gap-3">
						<span className="w-2 h-8 bg-blue-500 rounded-full"></span>
						Difficulty Summary
					</h3>

					<DifficultySummary data={data} isExport={true}/>
				</div>
			</div>

			{/* フッター */}
			<div className="mt-12 text-right text-slate-400 font-mono text-sm">
				Generated by CHUNI SCOPE
			</div>
		</div>
	);
});
