import { forwardRef } from 'react';
import type { ChuniData } from '../types';
import DifficultySummary from '../features/DifficultySummary';

interface LevelStatsExportViewProps {
	data: ChuniData;
}

export const LevelStatsExportView = forwardRef<HTMLDivElement, LevelStatsExportViewProps>(
	({ data }, ref) => {
		const { player } = data;

		return (
			<div
				ref={ref}
				className="bg-slate-50 font-sans text-slate-900"
				style={{ width: '1280px', minHeight: '600px', padding: '60px' }}
			>
				<div className="space-y-8">
					{/*ヘッダー*/}
					<div className="flex justify-between items-end border-b-4 border-blue-500 pb-4 mb-8">
						<div className="flex items-baseline gap-4">
							<h1 className="text-4xl font-black text-slate-800">{player.name}</h1>
						</div>
						<span className="text-blue-500 font-bold text-2xl tracking-widest">
							DIFFICULTY SUMMARY
						</span>
					</div>

					{/*難易度別*/}
					<DifficultySummary data={data} isExport={true}/>
				</div>

				{/* フッター */}
				<div className="mt-8 text-right text-slate-400 font-mono text-sm">
					Generated by CHUNI SCOPE
				</div>
			</div>
		);
	}
);

LevelStatsExportView.displayName = 'LevelStatsExportView';
